:main
	try
		1 / 0
		print("unreachable!")
	catch error
		print("fell into catch block")
	end
	print("finished catch block")
end
