:main
    try
        asdf()
        print("No error")
    catch
        print(error)
    end

    try
        this_throws_an_error()
    catch
        print(error)
    end

end

:this_throws_an_error
    throw "An error message"
end